export { Landing } from './Landing'
export { Skills } from './Skills'
export { Portfolio } from './Portfolio'
export { Footer } from './Footer'
export { Home } from './Home'
export { Contact } from './Contact'
